#source 'http://rubygems.org'
source 'http://ruby.taobao.org'

ruby "2.1.5"

gem 'rails', '~> 3.2.6'

gem "binding_of_caller", "~> 0.7.2", :group => :development
gem 'tilt','~> 1.3.2'

gem 'ezcrypto', '~> 0.7.2'
gem 'rack-protection', '~> 1.3.2'
gem 'memcache-client', '~> 1.8.5'

gem 'sidekiq', '~> 3.3.4'

gem 'certified', '~> 0.1.1'
gem 'bson_ext', '~> 1.8.2'
gem 'mongoid', " ~> 3.0"
gem 'mongoid_shortener', :path => "../mongoid_shortener"
gem 'kaminari', '~> 0.14.1'
gem 'httparty', '~> 0.10.1'

gem 'mime-types', "~> 1.21"
gem 'quill_common', :path => "../quill_common"
gem 'mobile-fu', "~> 1.1.1"

gem 'yab62', require: 'yab62'
# uploader

gem 'mini_magick', '~> 3.5.0'
gem 'carrierwave', '~> 0.8.0'
gem 'rack-raw-upload', '1.1.0'

# about mail

gem 'roadie', '~> 2.3.4'# html email
gem 'premailer-rails', '~> 1.4.0'
gem 'nokogiri', '~> 1.5.6'
gem 'rest-client', '~> 1.7'

gem 'alipay', :github => 'chloerei/alipay'
gem 'state_machine'
# gem "qrcoder", "~> 0.1.3"
gem 'rqrcode-rails3', "~> 0.1.7"
gem "slim", "~> 2.0.2"

gem 'gon', "~> 4.1.1"
gem 'whenever', :require => false

group :assets do
  gem 'sass-rails', '~> 3.2.6'
  gem 'coffee-rails', '~> 3.2.2'

  gem 'uglifier', '~> 1.3.0'
  # gem for handlebars_assets.
  gem 'handlebars_assets', '~> 0.14.1'

  # gem for compass.
  gem 'compass-rails', '~> 1.0.3'

  gem 'jquery-rails', "~> 2.2.1"
  # gem for bootstrap.
  gem "bootstrap-sass-rails", "~> 2.3.0.0"
  # gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails',
  #                             :github => 'anjlab/bootstrap-rails',
  #                             :branch => '3.0.0'
  # gem 'bootstrap-sass', '~> 2.1.0.0'
end

group :test do
  gem 'rspec-rails', '~> 2.13.2'
  gem "capybara", '~> 2.1.0'
  gem 'turn', '~> 0.9.6', :require => false
  gem 'factory_girl_rails', "~> 4.1"
end

group :development do
  gem 'thin'
  gem 'pry-rails', "~> 0.2.2"
  gem "better_errors", "~> 0.8.0"
end

group :production do
  gem 'passenger'#, '~> 3.0.19'
end
